import './globals.css'

export const metadata = {
  title: 'Portfolio Raúl Ortega',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='main'>
          {children}
      </body>
    </html>
  )
}
