import './globals.css'

import Head from 'next/head'

export const metadata = {
  title: 'Portfolio Raúl Ortega',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="preload" href="/_next/static/css/app/layout.css?v=1700629629965" as="style" />
      </Head>
      <body className='main'>
          {children}
      </body>
    </html>
  )
}
